### ISSUE TITLE
Sungear Dialog Arrows

### ISSUE THREAD

**Issue by radhikamattoo** [RajahBimmy/Sungear#47]
The bottom left corner with the two arrows and the circle in the center are cycling through the vessels, but when the mouse moves out of the sungear dialog it removes the highlight. W

When the center circle between the arrows is clicked, the selected set should be set to the highlighted vessel

**Comment by RajahBimmy** [comment]
1. Isn't something that happens normally in the original sungear and is actually a bug based on where the arrows hang.

2. Fixed and closed.
