### ISSUE TITLE
Vessel multiselect

### ISSUE THREAD

**Issue by radhikamattoo** [RajahBimmy/Sungear#48]
using ctrl to select multiple vessels highlights a second vessel in a red outline, and doesn't allow you to select any other vessels. When the second vessel is outlined, it doesn't set the selected set properly, so the go terms and genes don't highlight properly (and thus narrowing doesn't work properly)

**Comment by RajahBimmy** [comment]
@radhikamattoo this issue is caused by the `notNewSelection` method within `GeneList`. I didn't implement it, but when it's ignored, the dialog behaves correctly. I'll leave it up to you if you want to remove it, because I'm not aware of whether or not it breaks anything else you've written.

**Comment by radhikamattoo** [comment]
@RajahBimmy okay so i thought multiselect was with Option, cause when i tried it with Control a popup menu came up (maybe its just Mac? I tried it on other browsers and the behavior is the same). Now I see if you click again it does fulfill the multiselect properly (bless).

Do you know how to remove the popup menu for Control? There's the strange Option multiselect with red outlines and no `setSelection` call, so maybe we can use Option for the multiselect behavior instead? Lmk what you think

**Comment by RajahBimmy** [comment]
@radhikamattoo it's supposed to be the `cmd` button on a mac, not the `ctrl`. `ctrl` should trigger it on windows. The code I've written accounts for this and if you remove the `notNewSelection` function, it'll work.
